// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('example.app.static', []);

  app.controller('AppController', [
    '$scope', '$http', function($scope, $http) {
      $scope.sections = [];
      return $http.get('/restdocs/sections').then(function(result) {
        return angular.forEach(result.data, function(item) {
          return $scope.sections.push(item);
        });
      });
    }
  ]);

}).call(this);
